version: "3"

services:
  db:
    image: postgres
  dj:
    container_name: dj
    build: source
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - ./source:/code
    ports:
      - "8080:80"
    depends_on:
      - db